name: CI/CD Pipeline

on:
    push:
        branches:
            - main # Ao enviar um PUSH para main ele executara os 'jobs'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Roda um checkout para verificar se o projeto est√° ok
            - name: Checkout
              uses: actions/checkout@v2

            # Faz o login no Docker Hub para poder modificar a imagem
            - name: Login in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Faz o build da imagem e faz o push para o Docker Hub
            - name: Build and Push Docker Image
              # Troque 'k8s-ci-cd' pelo nome da sua imagem
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/k8s-ci-cd:latest . 
                  docker push ${{ secrets.DOCKER_USERNAME }}/k8s-ci-cd:latest

            # Inicia o Kubernetes
            - name: Set up K8s
              uses: azure/setup-kubectl@v1
              with:
                  version: "latest"

            # Faz o deploy do arquivo YAML no minikube
            - name: Deploy to Minikube
              run: |
                  kubectl apply -f k8s/deployment.yaml --validate=false
